= The Meaning of Types

One of the most common "code smells" that I've come across is one that goes by the name "Primitive Obsession". No, it's not a men's fragrance by Calvin Kline. It refers to the tendency that many developers seem to have to not want to define custom classes to model the problem domains for which they are developing software. More specifically, "Primitive Obsession" is the use of "primitive' or other built-in data types to represent domain concepts, rather than defining custom types to represent those concepts.

As best I can tell, the primary reasons that this code smell is so prevalent are 1) laziness on the part of the developer (a noble trait, but misguided in this case) and 2) ignorance of the "right way" to model their domain. In this article, I'll try to address both of these reasons.

== Exemplī Grātiā

In a past life, I worked as a consultant on a rather large Java project for a very large and important financial institution. The project was involved with trading certain types of financial securities. The standard way to identifying a financial security (in North America, at least) is the _CUSIP_ (which, incidentally, stands for _Committee on Uniform Security Identification Procedures_), a nine-character alphanumeric code that acts as a universal unique identifier for any security. The exact mechanism of generating CUSIPs is up to the institution issuing the security, but there are certain validation rules that can be applied, which are mainly intended to catch mistakes during manual data entry. For instance, the characters "I" and "O" are banned because they might be mistaken for "1" or "0", and the last character in each CUSIP acts as a checksum. 

Given such an important domain concept with well-defined validation rules, one would hope that all CUSIPs in the system would be represented by a dedicated `CUSIP` class that enforces those rules. However, as you might guess from the subject of this article, when I joined the project, these values were instead being represented as plain Java `String` objects throughout the system. There were XML schemas defined for the messages that were passed between system components, but even there, the validation rules merely indicated "9-character string" with no further validation beyond that, and no custom type bindings for the JAXB classes that were being generated to represent these messages.

As a result, a typical service interface that worked with CUSIPs might look like this:

----
public interface SecurityLookupService {
   Security findSecurityByCUSIP(String cusip) throws SecurityNotFoundException;
----

Let's consider the implications of representing CUSIPs as plain `String` objects.

First of all, the `String` class comes with no implication of any validation having been performed on its value. This means that any code that works with CUSIPs as `String` instances must make one of two assumptions:

1. Assume that any `String` it receives is potentially invalid and therefore defensively validate every input. In a large system, this means that *every* CUSIP may be validated many times as it moves throughout the system, and the validation logic will be repeated in every piece of code that works with CUSIPs. In the case of the above example interface, this might mean either throwing an `IllegalArgumentException` in this case, or simply throwing a `SecurityNotFoundException`, though I would argue that the latter solution would be undesirable, since the caller would not be able to tell whether the exception was thrown due to an invalid value or if the security was simply missing from the system.
2. Blindly assume that any `String` it receives has already been validated _somewhere_, and pray that there is no way for a CUSIP to enter the system via a path that does not include this validation. This was the approach that was taken by this project.

As you can see, both of these assumptions seem fundamentally flawed. In one, (hopefully) the same code will be duplicated all over the place (and perhaps not even consistently) and all callers would need to accept the possibility that a method call might value due to validation. In the other, everyone is putting blind faith into the idea that someone else has already done the work. Furthermore, there is no guarantee that every developer working on the system will make the same assumption, so you may see both approaches being used in various parts of the system.

An interesting - and disturbing - fact that I discovered in the course of investigating this state of affairs was that many, if not most, of the developers working on the project were not even aware of what a valid CUSIP should look like. Why should they? They weren't responsible for generating CUSIPs, and for the most part, they were just being treated as opaque values. However, an unfortunate side effect of this was that many developers were just using arbitrary strings as CUSIPs in the tests they wrote, and most of those strings were very clearly *not* valid CUSIPs. This meant that if someone made a change that added CUSIP validation logic somewhere that it did not previously exist, it would, in fact, cause these tests to fail. Indeed, I discovered that the test data being generated by the test team contained many invalid CUSIPs and other types of values. This meant that tests were effectively being written to verify that the system would accept data it should not have accepted! Given that the system needed to talk to external systems using these values in the course of performing multimillion-dollar financial transactions, this was not a very good situation.

The approach I took to attempt to rectify this situation was to create an immutable `CUSIP` class, and use that class wherever a CUSIP was expected in the modules I worked on. This produced a number of benefits:

1. Services that received an instance of `CUSIP` as input did not need to perform validation on the input, since validation had already been performed in the course of constructing the `CUSIP` object, and there was no for a `CUSIP` to come into existence without being validated.
2. There was no possibility that someone could inadvertantly pass a `String` representing some other type of value (not a CUSIP) where a `CUSIP` was expected, since such code would not compile.
3. Anyone looking at code using working with instances of `CUSIP` could immediately tell what type of value any variable, field, or parameter of type `CUSIP` was, since it would be right there in the name (unlike `String`, which doesn't tell you anything other than that it's a sequence of characters). This reduced confusion as well as cut down on the amount of documentation required.
4. As an added bonus, I included a `static` `randomCUSIP` method, which would return an randomly-generated CUSIP for use in tests. This eliminated the need for developers to think of CUSIP values while writing tests, since, ultimately, they did not care what the values were, only that they matched what was expected in a given test scenario. This also meant that the tests would be written using valid CUSIP values and not made up, usually invalid ones.

The importance of improving code clarity cannot be overstated. Many people talk about writing "self-documenting" code, but frequently that is just a euphemism for "*I* can tell what it does. Why can't you?" The type system is one of the most effective ways to make code truly self-documenting, but I will elaborate on that more later. First, I want to go into a bit more detail about point #2 above, regarding inadvertantly mixing up values.

== A Tale of Two Identifiers

On the subject of mixing up unrelated values because they are the same type, some people might argue "If you just give variables descriptive names, then that shouldn't be a problem." That argument is foolhardy for several reasons:

1. Even if named descriptively, variables might have similar names because the things they represent are similar (but not the same), and therefore someone might still get them confused.
2. In most programming languages (including Java, in particular), method/function arguments are matched to parameters based on the order they appear in the method/function signature and function call (though some languages, such as Scala, allow passing named arguments in any order, which alleviates this to some degree), so it's possible to mix up parameters of the same type just by getting the order wrong. This is even made worse when methods/functions are overloaded, in which case it may be possible to inadvertently call the wrong overloaded version of the method by forgetting to include an argument.
3. Relying on the developer's ability to keep track of variable names provides no peace of mind for the developer, who must continually inspect every line of code for possible mistakes.

Aside from CUSIPs, the project mentioned above worked with many other types of identifiers. Many of these were simply integer values, with the only validation rules, if any, being restrictions on the number of digits and whether negative values were allowed. At the point when I started working on the project, all of these identifiers were represented by the Java primitive type `long`.

One module that I worked on operated on a particular domain object, which here I will call `FooPiece`, and additional domain objects representing bundles of these, which I will here call `FooBundle`. Each of these domain object classes had a numeric identifier associated with it. These identifiers, when assigned to variables verbosely, were typically called `fooPieceIdentifier` and `fooBundleIdentifier`, respectively. However, some developers found typing out variable names like these to be cumbersome, and soon started using abbreviated names like `fooId` and `fooBId`. It wasn't long before I came across a line of code that used `fooId` where `fooBId` should have been passed, due to some careless keystrokes. What made it worse was that the tests for this code didn't really care about the identifier values, and the mistake was so small that it slipped by the code reviewers, so the bug wasn't detected until later when I happened to spot it while making a change to support a new feature.

Had the code in question been working with classes named `FooPieceIdentifier` and `FooBundleIdentifier`, the mistake would have been caught right away, because the attempt to use a `FooPieceIdentifier` where a `FooBundleIdentifier` was expected wouldn't have gotten past the compiler's type checker.

== But what does it all mean?

It seems to me that many developers are stuck in a C mindset when it comes to types. In C, types primarily exist to define how data is stored in memory (indeed, you'll see the phrase "storage type" in some C and C++ compiler messages). Many developers seem to have carried this over to other, higher-level languages, such as Java, thinking of types only as a way to keeping track of how data is stored, and not as a way to impart semantic meaning to data. However, even C supports type aliasing (via `typedef`), which at least provides a very crude (and not nearly foolproof) mechanism by which a developer can try to signal the intent of what a particular value is to mean.

A data type associates three pieces of information with a value:

1. The in-memory representation of the value.
2. The set of operations that are valid to be performed on that value.
3. *The semantic meaning of the value in the domain of the application.*

The first point seems to be the one that most developers focus on, yet it is the *least* important for anyone _using_ a particular value. In fact, the internal representation of a data type has _no bearing whatsoever_ on how that data fits into the functional requirements of the system. An application working with CUSIPs need not care how `CUSIP` instances are internally represented. It needs only know that a particular value a) is a CUSIP and b) can be manipulated using a particular set of operations. The internal storage may only be important to satisfy non-functional, performance-related requirements, but in most cases that is seldom an important concern.

The third point is highlighted because it is the most overlooked yet generally the most important for modeling a problem domain properly. For the sake of writing clean, understandable, and reliable code, *a type should clearly express the _meaning_ of a piece of information in the context of the application*. Additionally, a given concept should be expressed by exactly one type throughout the system, even if it may in stored or displayed in different formats (and those different formats may be obtained via conversion operations on the type itself, or by separate format objects, as appropriate). Furthermore, each type should _precisely_ describe the concept it represents, with no more information than necessary, and no less. A date and a timestamp are two separately concepts, though related, and therefore they should be represented by separate types, though those types may be related as parts of the same inheritance hierarchy, for example.


== Nullifying Null

The null reference was (arguably) invented (for statically typed languages, at least) in 1965 by the computer scientist Tony Hoare (of Quicksort fame) for the ALGOL W programming language. Since then, this invention has been replicated in many other languages, including Java.

For his part, Dr. Hoare refers to his invention as his "billion dollar mistake". He does not mean this as hyperbole or exaggeration. He literally means that he believes that a billion dollars is a pretty good ballpark figure for the amount of real damage that has resulted from errors caused by null references in the past half a century.

The main problem with null references is that they undermine the type system. Any given reference can _either_ point to an object of the specified type _or_ nothing at all, and it's entirely up to the developer to keep track of whether any given value might be null. Runtime errors result if the developer neglects to check for null when it is necessary, and unnecessary null checks result in useless and confusing code.

Some languages, such as Kotlin and Ceylon, attempt to wrangle null references by adding special syntax to indicate what variables are "nullable". Other languages provide special types, such as Haskell's `Maybe` and Scala's `Option`, that act like immutable containers of zero or one element. Both approaches force developers to deal with missing values explicitly, under penalty of a compile-time error if you forget (rather than having to wait for a `NullPointerException` at runtime). Java 8 takes the latter approach, providing the generic http://docs.oracle.com/javase/8/docs/api/java/util/Optional.html[`java.util.Optional`] class. 

You obtain an empty instance by calling `Optional.empty()`, and you obtain an instance that has a value by calling `Optional.of(value)`. When interacting with code that uses `null` instead of `Optional`, you can also convert a nullable value to a (not null) `Optional` by calling `Optional.ofNullable(valueOrNull)`, and you can convert it back to a possibly-null value by calling its `orElse` method with an argument of `null`. When receiving an instance of `Optional`, you can either use an `if` conditional to check its `isPresent()` method to check whether it has a value (which can be obtained using its `get` method), or you can lambdas with other methods to specify actions to be performed if and only if the value is present.

For earlier versions of Java, the Guava library provides a similar class, also named http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Optional.html[`Optional`]. Its methods are named slightly differently, but it works in more or less the same way as the Java 8 `Optional`. 

Using the `Optional` class for method and constructor parameters makes it obvious which values are, well, optional, without the need for the caller to consult documentation. For return values, it makes it clear that a particular method might not return a value. Take the following query service interface as an example.

----
public interface UserLookupService {
   Optional<User> findUserByName(UserName username);
   List<User> findActiveUsers(Optional<Duration> maxIdleTime);
}
----

Even without any documentation, it is immediately obvious that `findUserByName` will return an empty `Optional` (rather than `null` or throwing an exception) if it cannot find the specified user, and it is also clear that the `maxIdleTime` parameter of `findActionUsers` is not a required value. Futhermore, if you are diligent about always using `Optional` and not `null` throughout your codebase, you can be reasonability certain that `null` is not a valid argument to pass to either method, and that neither method will ever return `null` (and doing so would be considered a bug).

I strongly encourage all Java developers to banish `null` completely from their projects. Always use `Optional` to represent potentially missing values. Wherever you must interact with code that deals in nulls (such as `java.util.Map`, whose `get` method returns `null` if no element matches the specified key), always immediately wrap the nullable value in an `Optional`, and convert back to a nullable value only precisely when needed. The only other place where `null` may legitimately appear is in initialization logic, where it may show up as a temporary state of a field that has not been initialized yet (e.g., because the constructor of the enclosing object hasn't finished executing yet). If a `null` appears at any other time, it should be treated as if the containing scope is in an illegal state, and therefore a likely bug.

You may be tempted to forgo the ceremony associated with wrapping a nullable value in an `Optional` when that value is only going to be immediately checked for "null-ness" (or "non-null-ness") and then forgotten (such as when you are doing something as simple as `if (foo.bar() != null)`). However, letting _any_ null creep into your code yields a slippery slope towards chaos and confusion. A few extra keystrokes (such as replacing the previous example with `if (Optional.ofNullable(foo.bar()).isPresent())`) is a small price to pay for the piece of mind and code clarity that is attained by ensuring that all optional values are diligently and _consistently_ captured as instances of `Optional`.



