= On the Subject of Finality
:hp-tags: programming, Java, final, immutability

This is the second installment in the _How to Make Your Java Code Not Suck_ series.

== Fightin' (key)words

When debating Java code style, the one issue that has probably gotten me into the greatest number of heated arguments is the appropriate use of the keyword `final`. I am not alone in my views on the subject, but it seems that there are great unwashed masses of developers who have not yet been converted to the *Church of `final`*, and some of them seem to get quite annoyed when they see `final` used in places where it is not absolutely required.

However, before I go into detail on what my exact position is on the subject, and why nonbelievers are doomed to burn in Mutability Hell, let's recap what, exactly, `final` means when it appears in Java code.

== Final Overload

First of all, any Java programmer worth his or her salt knows that `final` actually has two completely different meanings in Java, depending on where it is used.

The first, and probably most commonly used, meaning of `final` is as a modifier on declarations variables, fields, and parameters. When applied in front of one of these, it effectively makes the identifier a constant for the duration of his scope. This means that once the identifier is initialized, the value it refers to cannot be changed. Its use is generally mandated when defining constants (especially in conjuction with the `static` keyword), and prior to Java 8, its use was required by the compiler whenever an anonymous class creates a closure around a variable in the enclosing scope. For primitives, the use of `final` effectively makes the variable a true constant (within its scope), but when applied to objects, it only makes the reference constant, but not the object itself, so care must be taken to not confuse the two concepts.

The second, less commonly used (and probably less well understood), meaning of `final` is as a modifier on classes and methods to restrict inheritance and method overriding. Applying `final` to a class prevents the creation of subclasses that extend it. Applying `final` to a method prevents subclasses from overriding that method.

I am primarily concerned with the first meaning of `final` in this article, though I will touch on the second a bit as well.

== Final Thesis

Now that we have covered the meanings of `final`, we come back to the subject of when it ought to be used.

After experimenting with different styles over the course of several years, I have settled upon the strongly held conviction that *`final` should be applied to _all_ fields, parameters, and variables except for cases where the value definitely needs to change over time* (and only after considering the alternatives). The sole exceptions to this rule are constants defined on interfaces, which are implicitly `final` without needing to use the keyword, and parameters of abstract methods, where `final` has no effect.

== Preemptive Strike

Before I go on to answer the question of "Why?", I will first preemptively counter the reasons I've heard for "Why not?".

The most common argument against that I've heard when I have argued in favor of liberal use of `final` is that it "clutters up" the code with all those "extra" keywords. To that I have the following things to say:

1. It's only an extra 5 characters (6 if you count the space). It's not like there's a worldwide letter shortage or something. There's a little extra typing involved, but it's not so much as to be cumbersome.
2. In an IDE or a text editor with Java syntax highlighting, those `final` keywords at the beginnings of lines will appear in a different color than the surrounding text, providing you with  nice visual markers of where your variable declarations are.
3. If you're concerned about verbose source code, Java is _not_ the language for you. Address all complaints to James Gosling.
4. Purely cosmetic concerns take a back seat to functional ones.

